# Generated by Django 5.1.6 on 2025-05-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_show_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='category',
            field=models.CharField(choices=[('concert', 'Concert'), ('theatre', 'Théâtre'), ('cinema', 'Cinéma'), ('comedy', 'Comédie'), ('dance', 'Danse'), ('other', 'Autre')], default='other', max_length=20),
        ),
    ]
